# Generated by Django 2.2.5 on 2020-11-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20201116_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='country',
        ),
    ]
