# Generated by Django 2.2.5 on 2020-11-26 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PstType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Pst Type',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Pst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pst_name', models.CharField(max_length=20)),
                ('pst_content', models.TextField()),
                ('pst_img', models.ImageField(blank=True, upload_to='pst_imgs')),
                ('pst_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psts', to='psts.PstType')),
                ('pst_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='pst_photos')),
                ('pst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='psts.Pst')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
