# Generated by Django 2.2.5 on 2020-11-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201125_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cpation',
            new_name='caption',
        ),
    ]
