# Generated by Django 2.2.5 on 2020-11-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201125_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blogs.Blog'),
        ),
    ]
