# Generated by Django 2.2.5 on 2020-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201108_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confrimed', 'confrimed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
